module.exports = {
  entities: {
    plants: {
      label: 'plants',
      entity: 'Plants',
      displayField: 'Name',
      uri: '/api/v1/plants',
      initMenu: true,
      icon: '&#xe199;',
    },
    products: {
      label: 'products',
      entity: 'Products',
      displayField: 'Name',
      uri: '/api/v1/products',
      initMenu: true,
      icon: '&#xe011;',
    },
    posts: {
      label: 'posts',
      entity: 'Posts',
      displayField: 'OrderID',
      uri: '/api/v1/posts',
      icon: '&#xe167;',
    },
  },
  router: {
    hedging: {
      title: 'Hedging',
      allowed: true,
      path: '/hedging',
      component: 'Hedging',
      componentPath: 'Hedging/Hedging',
      routes: [
        {
          title: 'Plants',
          path: '/hedging/plants',
          uri: '/api/v1/plants',
          component: 'HedgingPlants',
          componentPath: 'Hedging/HedgingPlants',
          collection: 'plants',
          routes: [
            {
              exact: true,
              title: 'Plant Detail',
              collection: 'products',
              path: '/hedging/plants/:id',
              component: 'HedgePlantDetail',
              componentPath: 'Hedging/HedgePlantDetail',
            },
            // {
            //   exact: true,
            //   title: 'Test',
            //   path: '/hedging/plants/:id/:id',
            //   component: 'HedgePlantDetail',
            //   componentPath: 'Hedging/HedgePlantDetail',
            // },
          ],
        },
        {
          title: 'Products',
          collection: 'products',
          path: '/hedging/products',
          uri: '/api/v1/products',
          component: 'HedgeContent',
          componentPath: 'Hedging/HedgeContent',
        },
      ],
    },
    category: {
      title: 'Exo 1',
      allowed: true,
      path: '/category',
      component: 'Categories',
      componentPath: 'Categories/Category',
      routes: [
        {
          path: '/:category',
          title: 'Exercice 1',
          allowed: true,
          component: 'CategoryDetail',
          componentPath: 'Categories/CategoryDetail/CategoryDetail',
        },
      ],
    },
    app3: {
      title: 'App 3',
      allowed: false,
      exact: true,
      path: '/app3',
      component: 'Appli3',
      routes: [],
    },
  },
  initNavMenu: ['plants', 'products'],
};
